### ISSUE TITLE
can not log in

### ISSUE THREAD

**Issue by xfjx** [reduzent/watchteleboy#19]
Does this script work anymore?

I can not login with my credentials. Anyhow it looks as if it logged in cause it creates cookie files in temp dir but I get an error message.

Already logged in as XXX
Could not extract a valid user id

Thank you very much!

**Comment by xfjx** [comment]
I had a special character in my password that was causing the problem m(

Now I get an other error message: 

receiving channel list...failed

**Comment by reduzent** [comment]
Hey

Thanks for your report. I noticed the problem, too. Probably teleboy.ch changed something in their web front-end. There is some code in watchteleboy that assumes a certain structure on certain pages for extracting things like the channel list. I'll let you know when I was able to fix it.

Cheers

**Comment by reduzent** [comment]
There is some good and some bad news. First the bad news: The channel list cannot be extracted from html anymore, since they moved it into some javascript trickery. I don't have a clue how to extract the available channels and their channel ids anymore. The good news is that they didn't reduce the number of channels available for free, but one has to subscribe to channels in order to play them.

**Comment by reduzent** [comment]
Ok, got it fixed. I found there is a much cleaner way to get the channel list from the teleboy api directly. However, in order to be able to parse the JSON output in a sane way, I decided to add another dependency to the scripts: jq. I will refactor some code in the future, so that jq is always used for JSON parsing. 

IMPORTANT NOTE: watchteleboy will only list the subscribed channels. What people are now supposed to do is to log in to the teleboy website and subscribe to all channels of interest. Also, you can order the channel list there and watchteleboy will list the channels in the same order.

Have Fun!
